apiVersion: v1
kind: Namespace
metadata:
  name: ns-a

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-a
spec:
  hard:
    cpu: "10"
    requests.cpu: "10"
    memory: "50Gi"
    requests.memory: 10Gi



#jakis comment
