apiVersion: v1
kind: Namespace
metadata:
  name: ns-a

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-a
spec:
  hard:
    limits.cpu: "1"
    limits.memory: 2Gi
