apiVersion: v1
kind: Namespace
metadata:
  name: ns-a

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-a
spec:
  hard:
    cpu: "2"
    requests.cpu: "2"
    memory: "5Gi"
    requests.memory: 1Gi


#jakis comment
