apiVersion: v1
kind: Namespace
metadata:
  name: ns-a

------

apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: ns-a
spec:
  hard:
    limits.cpu: "3"
    limits.memory: 5Gi
    cpu: "4"
    memory: "7Gi"
