apiVersion: v1
kind: Namespace
metadata:
  name: ns-b

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-b
spec:
  hard:
    cpu: "1"
    requests.cpu: "1"
    memory: "1Gi"
    requests.memory: 1Gi
