apiVersion: v1
kind: Namespace
metadata:
  name: ns-b

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-b
spec:
  hard:
    cpu: "2"
    requests.cpu: "2"
    memory: "2Gi"
    requests.memory: 2Gi
