apiVersion: v1
kind: Namespace
metadata:
  name: ns-b

------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: ns-b
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 5Gi
    cpu: "2"
    memory: "7Gi"
